import type { Metadata } from 'next';
import AntdRegistry from './providers/antdRegistry';

import 'src/styles';

export const metadata: Metadata = {
  title: 'Grin Admin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="grin-app">
          <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
